### ISSUE TITLE
Mac OS joystick not initialized

### ISSUE THREAD

**Issue by artem469** [joncoop/pygame-xbox360controller#5]
Hi! I try to run your example on mac os and I have this trouble:
Traceback (most recent call last):
  File "/Users/artem/PycharmProjects/desktopCli/main.py", line 16, in <module>
    joy_controller = xbox360controller.Controller(0)
  File "/Users/artem/PycharmProjects/desktopCli/xbox360controller.py", line 105, in __init__
    self.joystick = pygame.joystick.Joystick(Controller.id_num)
pygame.error: joystick system not initialized

driver is installed and work fine (360Controller 1.0.0-alpha.5)

**Comment by artem469** [comment]
Sorry, figured it all out myself
